### ISSUE TITLE
Option to download zip of currently viewed directory?

### ISSUE THREAD

**Issue by zachlysobey** [KinoLien/gitzip#1]
Cool project! Found on StackOverflow.

It would perhaps be a good enhancement to enable downloading a zip of the current directory.

That is, when viewing a directory of files, you have to go *up* a level in order to download it as a zip. This was pretty confusing to me at first.

I assumed (as I'm sure a few other users would) that you would search for a folder, then be able to download it, but thats not *quite* how it works. 

Hope this made sense. I'd be happy to clarify, or even help implement this change (perhaps) if you need it.

**Comment by KinoLien** [comment]
In fact, it also confusing to me when I was designing the page. 

I thought somebody (like me) wants to view the folder contains files and also wants to download zip immediately after press Enter.

So I think your opinion is make sense. User friendly is important thing.

Thanks a lot. I will improve this in few days.

**Comment by zachlysobey** [comment]
sweet!
