### ISSUE TITLE
Plain web version

### ISSUE THREAD

**Issue by bfred-it** [KinoLien/gitzip#16]
It'd be nice if the web version had no UI for direct links like:

https://kinolien.github.io/gitzip/?download=https://github.com/KinoLien/gitzip/tree/gh-pages

Opening this link should start the download immediately. The only UI should be a progress circle, like [this one](https://codepen.io/LFeh/pen/vGMJBN), but with a file count instead of % (like *3/**20***)
<img width="119" alt="progress circle" src="https://user-images.githubusercontent.com/1402241/34569777-6575d58c-f19c-11e7-9c8e-5919e196953e.png">

If this is implemented, we might include a link from [Refined GitHub](https://github.com/sindresorhus/refined-github/issues/815)

**Comment by styfle** [comment]
There is a similar project, [DownGit](https://github.com/MinhasKamal/DownGit,) that has a [web interface](https://minhaskamal.github.io/DownGit) that supports this syntax.

> A typical download URL will look like this- `https://minhaskamal.github.io/DownGit/#/home?url=<link>&fileName=<name>&rootDirectory=<true or false or name>`

**Comment by bfred-it** [comment]
Great! Thanks :)

**Comment by bfred-it** [comment]
It turns out that the API is required for a few big projects, example: 

https://github.com/Microsoft/vscode/tree/master/src

https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/Microsoft/vscode/tree/master/src

**Comment by bfred-it** [comment]
I built it: https://download-github-dir.bfred.it/
