### ISSUE TITLE
Services no longer works ?

### ISSUE THREAD

**Issue by Moe-Baker** [KinoLien/gitzip#31]
Did GitHub block this service with a new policy update? it seems so, the web page gives these errors when trying to download anything:
`'http://kinolien.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
It's a shame, this was more convenient than just downloading the entire repository.

**Comment by ret394** [comment]
Works fine. Tested twice.

Just follow https://github.com/KinoLien/gitzip/blob/gh-pages/get-token-step.md
- Copy and paste the token.
- Then paste your target Github URL. for ex- `https://github.com/KinoLien/gitzip/tree/master/js`

---

You can get the CORS policy messages if you use your Github PA token. It's a common point of confusion, so please don't skip this app. The link to steps could be made more prominent on the page https://kinolien.github.io/gitzip/.

You need to generate one for GitZip app using the steps specified.

Once generated you can manage token in 'Authorized OAuth Apps' in Github settings-> Applications.

thanks. have a nice day. keep up the great work. 👏

[ret394](https://github.com/ret394)

**Comment by Moe-Baker** [comment]
Thank you all for the follow up, it works now!
