### ISSUE TITLE
Support of New Repo Layout

### ISSUE THREAD

**Issue by ro-n** [KinoLien/gitzip#32]
![Screen Shot 2020-06-10 at 9 15 34 AM](https://user-images.githubusercontent.com/66688118/84216068-f9efa700-aafa-11ea-9216-71ac7d500511.png)

Hi there,

Seems GitHub will support a new UI of repositories, any ideas of a reimplementation?

**Comment by KinoLien** [comment]
I don't get the message yet. Would you give a link about this information?

**Comment by ro-n** [comment]
Link is [here](https://gist.github.com/broccolini/2245234ac3a4936049e8ffc13f376986), I've tested it on current `gitzip` and it doesn't work, seemingly double clicks redirecting nowhere.

**Comment by KinoLien** [comment]
I followed the instruction and navigate to **Profile dropdown > Feature Preview**, but **Repository design updates**  was not found. (Maybe I'm not in the list of beta users) 
Therefore I can't enhance the compatibility of `gitzip`, at least in the near future.

Or maybe could you do me a favor? I wanna know the html hierarchies of new layout.
In repo page > Open `Inspect` tool > Select the directory or file icon > take a screen shot
Just like this:
![screenshot](https://user-images.githubusercontent.com/8223275/84342872-3e517480-abd9-11ea-8571-9b617137d8f4.png)
It would be very helpful!

**Comment by ro-n** [comment]
Sure for that, will this be helpful?
![image](https://user-images.githubusercontent.com/66688118/84973139-ef648b80-b152-11ea-8515-1eddf490de6b.png)

**Comment by KinoLien** [comment]
Thank you for the screen shot, and fortunately, I get the notification of `Feature Preview` today :-)
![Preview](https://user-images.githubusercontent.com/8223275/85267912-662dbb80-b4a8-11ea-8b6c-6faf912b8e27.png)

**Comment by KinoLien** [comment]
It has fixed on Chrome extension v0.4.0 and Firefox addon v0.3.0.
