### ISSUE TITLE
Offer downloading via GET parameter

### ISSUE THREAD

**Issue by julmot** [KinoLien/gitzip#5]
e.g. http://kinolien.github.io/gitzip/?download=myrepo/folder

**Comment by KinoLien** [comment]
Currently, i don't have plan to setup server to implement it.
And this site is pure client, so if i do this, It will have some "features", like:
you cannot use command `curl` (or similar) to request, (only get html, not file)
you cannot use `XMLHttpRequest` to request in javascript, (only get html, not file)
you can use this url in the browser address bar,
you can use `<iframe>` to request this url.

So, is this what you need? or any ideas? please let me know, thanks.

**Comment by julmot** [comment]
@KinoLien You can also determine the specified parameters with JS and then deliver the ZIP
