### ISSUE TITLE
[IP Limit] API rate limit exceeded for IP ADRESS

### ISSUE THREAD

**Issue by onlylemi** [KinoLien/gitzip#6]
hey,

I try it. And it is good. But when use it long time, it doesn't work. The message is `API rate limit exceeded for IP ADRESS`. Now I don't use it.  I look github developer `rate limit`.

> #### Rate Limiting
 For requests using Basic Authentication or OAuth, you can make up to 5,000 requests per hour. For unauthenticated requests, the rate limit allows you to make up to 60 requests per hour. Unauthenticated requests are associated with your IP address, and not the user making requests. Note that [the Search API has custom rate limit rules](https://developer.github.com/v3/search/#rate-limit).

I want to know that, it have any solution methods. If you know, please tell me. Thank you.

**Comment by KinoLien** [comment]
I'll try to fix it in a few days, and then share the solution here.

**Comment by onlylemi** [comment]
hey @KinoLien 

Thank you. Look forward to your solution.

**Comment by KinoLien** [comment]
#### Register Application
[Register a new OAuth application](https://github.com/settings/applications/new)
"Authorization callback URL" means the url you want users redirect to after authorized.

#### Use IDs
Use hyperlink `<a href="https://github.com/login/oauth/authorize?scope=user:email&client_id=xxxxx">Auth</a>` in HTML;  ([see scope](https://developer.github.com/v3/oauth/#scopes))

#### Redirect Back
Github will redirect back like this: `http://your.site/and/path?code=xxxxxxx` after authorized.

#### Post the "code" token to OAuth API
Use "POST" method request to `https://github.com/login/oauth/access_token`, and parameter includes client_id, client_secret, code. You can do it by server side or client side, but client side has CORS issues. In my case, I use form submit to skip(avoid?hack?) this problem.

#### Gets Token
After form submit, it'll return a file and content like: `access_token=abcdefg1234567xxxxx&scope=user%3Aemail&token_type=bearer`. 
Now, use `access_token` to access GitHub API, and you can make up to 5,000 requests per hour. (Unauthenticated only 60 requests)

**Comment by julmot** [comment]
?

**Comment by julmot** [comment]
Sorry, I don't see any commit that solves this issue.
