### ISSUE TITLE
URL parameters needs slash after gitzip?

### ISSUE THREAD

**Issue by jamiewilson** [KinoLien/gitzip#9]
I was having trouble creating a direct link to download following the url parameters. But adding a slash after `gitzip` seems to work:

Without slash:  
> https://kinolien.github.io/gitzip?download=https://github.com/nylas/N1/tree/master/internal_packages/ui-darkside

With slash:
> https://kinolien.github.io/gitzip/?download=https://github.com/nylas/N1/tree/master/internal_packages/ui-darkside

Thanks for creating this! Really cool!

**Comment by KinoLien** [comment]
Oh my fault, it may also makes someone else confused. :'(
Thanks to @peter-kehl for fix it.
